# Generated by Django 3.1.3 on 2020-12-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
